services:
  backend:
    container_name: hr-guardian-backend
    build:
      context: ./Backend
      dockerfile: dockerfile
    environment:
      SECRET_KEY: beablodola
      ALGORITHM: HS256
      DATABASE_URL: postgresql://hr_api:hr_api_pass54321@api-database:5432/hr
    command: --root-path /api
    depends_on:
      api-database:
        condition: service_healthy

  api-database:
    image: postgres:17
    container_name: hr-guardian-database
    environment:
      POSTGRES_DB: hr
      POSTGRES_USER: hr_api
      POSTGRES_PASSWORD: hr_api_pass54321
    ports:
      - "10230:5432"
    volumes:
      - api-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hr_api -d hr" ]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    image: nginx:stable-alpine
    container_name: hr-guardians-gateway
    volumes:
      - ./.nginx/:/etc/nginx/conf.d/
    ports:
      - "10000:80"
    command: nginx -g "daemon off;"
    depends_on:
      - backend
      - frontend
      - rag
      - ollama

  frontend:
    environment:
      - API_URL=127.0.0.1:10000
    build:
      context: ./FrontEnd/
      dockerfile: Dockerfile
    container_name: hr-guardian-frontend

  rag:
    container_name: hr-guardian-rag
    environment:
      - name=value
    build:
      context: ./RAG
      dockerfile: dockerfile
    command: --host 0.0.0.0 --port 9000 --root-path /rag
    volumes:
      - vectordb:/app/vectordb:rw

  ollama:
    build:
      context: ./CustomModel
      dockerfile: dockerfile
    container_name: ollama
    volumes:
      - ollama:/root/.ollama:rw

volumes:
  api-data:
  vectordb:
  ollama:


