services:
  backend:
    container_name: hr-guardian-backend
#    image: "imagename" #Указать ссылку на образ
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@api-database:5432/${POSTGRES_DB}
      RAG_URL: rag:9000
    command: --root-path /api/api
    depends_on:
      api-database:
        condition: service_healthy
    env_file:
      - .env

  api-database:
    image: postgres:17
    container_name: hr-guardian-database
    ports:
      - "${DB_OPEN_PORT:-5435}:5432"
    volumes:
      - api-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hr_api -d hr" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  gateway:
    image: nginx:stable-alpine
    container_name: hr-guardians-gateway
    volumes:
      - ./.nginx/:/etc/nginx/conf.d/
    ports:
      - "${APP_PORT:-80}:80"
    command: nginx -g "daemon off;"
    depends_on:
      - backend
      - frontend
      - rag
      - ollama
    env_file:
      - .env

  frontend:
#    image: "imagename" #Указать ссылку на образ
    container_name: hr-guardian-frontend
    env_file:
      - .env

  rag:
    container_name: hr-guardian-rag
#    image: "imagename" #Указать ссылку на образ
    command: --host 0.0.0.0 --port 9000 --root-path /api/rag
    volumes:
      - vectordb:/app/vectordb:rw
    env_file:
      - .env

  ollama:
#    image: "imagename" #Указать ссылку на образ
    container_name: ollama
    volumes:
      - ollama:/root/.ollama:rw
    env_file:
      - .env

volumes:
  api-data:
  vectordb: 
  ollama:


