FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt ./

RUN pip install --no-input -r requirements.txt

COPY ./ ./

ENV DATABASE_URL="postgresql://postgres:postgres@HOIST/HR"
ENV ALGORITHM="HS256"
ENV SECRET_KEY=23

EXPOSE 4000

ENTRYPOINT [ "uvicorn", "--host", "0.0.0.0:4000", "main:app" ]
