FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt ./

RUN pip install --no-input -r requirements.txt

COPY ./ ./

EXPOSE 4000

ENTRYPOINT [ "uvicorn", "--host", "0.0.0.0", "--port", "4000", "--forwarded-allow-ips", "'*'", "main:app" ]
