FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt ./

RUN pip install --no-input -r requirements.txt

COPY ./ ./

RUN mkdir vectordb

EXPOSE 9000

ENTRYPOINT [ "uvicorn", "--host", "0.0.0.0", "--port", "9000", "--reload", "--forwarded-allow-ips", "'*'", "main:app"]
